### ISSUE TITLE
Created DIV element sometimes interferes with the page

### ISSUE THREAD

**Issue by cafehaine** [miraks/Tap-Translate#12]
See here https://www.w3schools.com/css/tryit.asp?filename=trycss3_animation2
The second "square" is created by Tap-Translate.
A solution could be to add the style="display:none !important" attribute to fix this ?
(By the way, great addon, I use it all the time :) )

**Comment by miraks** [comment]
I'll fix this when Firefox 63 will be released with shadow DOM support

**Comment by miraks** [comment]
Addon was updated. This bug will be gone with Firefox 63 release.
