### ISSUE TITLE
Hi ! Please add the offlines pack of Google translate  :D

### ISSUE THREAD

**Issue by LifeIsStrange** [miraks/Tap-Translate#5]
Thanks for your awesome work !!

**Comment by miraks** [comment]
Hi. I will check if it possible to do this on the weekend.

**Comment by LifeIsStrange** [comment]
Oh, thanks a lot you are amazing ! 
On Android the offlines pack are downloadable in the Options of the app, you can use à network analyser to see the url of the downloads, if you don't find, I can help you but I don't know nothing about code and programmation  :m.

**Comment by LifeIsStrange** [comment]
Hey what's up about the Feature ?

**Comment by miraks** [comment]
Hey. Honestly I completely forgot about this issue, but anyway now this add-on is a webextension and it's now longer possible to provide offline translations. Sorry.
