### ISSUE TITLE
Tap translate does not work anymore on Firefox 42, 43, 44 and 45. 

### ISSUE THREAD

**Issue by LifeIsStrange** [miraks/Tap-Translate#6]
I can do tests for help you to fix.

**Comment by miraks** [comment]
Hi, sorry for long response. It only doesn't work for me on Nightly, I'll fix it this weekend. Can you check it again on 42-44, please?

**Comment by LifeIsStrange** [comment]
Hi :) 

Sorry finaly it work on 42/43 but not on 44/45. 
When I manually enable tap translate it work on 44/45 but when I close the app and I restart, tap translate don't work any more and is enabled on the settings.  So I need to manually disable /renable for it again work. And when I reclose the app, same bug etc... 
Sorry for my bad english, I can do tests for you on Android L

**Comment by miraks** [comment]
I've just published the new version. You can try it here https://addons.mozilla.org/en-US/android/addon/tap-translate/versions/ until it reviewed. See if it fixes this for you.
I'm not a native speaker, either :)

**Comment by LifeIsStrange** [comment]
Awesome it works good on 44/45 :D thanks !!

**Comment by miraks** [comment]
Great!

**Comment by LifeIsStrange** [comment]
Finally same bug :( on aurora ans nightly for Android.

**Comment by miraks** [comment]
Yeah, google translate api has changed. I have just uploaded new version, it should become available soon.

**Comment by LifeIsStrange** [comment]
You are awesome!
