### ISSUE TITLE
Firefox android 57.0

### ISSUE THREAD

**Issue by Alexey71** [miraks/Tap-Translate#7]
Hi. Add support new version browser please
![screenshot_20170903-111721](https://user-images.githubusercontent.com/10572914/30001534-d72fed84-9099-11e7-973b-fe4459267d0b.png)

**Comment by miraks** [comment]
Hello. Unfortunately [contextMenus API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus#Browser_compatibility) is still not available for Firefox for Android WebExtensions. So it isn't possible to exactly recreate this extension for FF 57+. Still it's possible to use [pageAction API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) instead. It'll be a little uglier (for my taste at least) but will do as a temporary solution. I'm going to try to release FF57-compatible version in a few days.

**Comment by Alexey71** [comment]
Add?

**Comment by miraks** [comment]
I didn't have much free time recently. Probably will be able to finish this weekend.

**Comment by miraks** [comment]
I've just uploaded new version of the add-on. It'll become available after review.
