### ISSUE TITLE
Where is the button?

### ISSUE THREAD

**Issue by ballsystemlord** [miraks/Tap-Translate#8]
Hello,
I'm using FF 56.0 and just downloaded and installed Tap-Translate.
I wanted to translate http://flashboot.ru/ (ru->en) but, when I hit your button, I get "Failed to laod translation".
OK, why does it fail?
Thanks

**Comment by miraks** [comment]
Hello.
Does issue still exist? If yes, which part of the page do you try to translate?

**Comment by ballsystemlord** [comment]
On Thu, 19 Oct 2017 13:48:05 +0000 (UTC)
Alexey Volodkin <notifications@github.com> wrote:

> Hello.
> Does issue still exist? If yes, which part of the page do you try to
> translate?
> 

Yes, I try to translate the whole page.

Thanks!
